FROM node:22-alpine

ENV NODE_ENV=production
WORKDIR /app
COPY server/package*.json ./
RUN npm install --omit=dev
COPY server/ .
RUN mkdir -p /tmp/kujuatime/uploads /tmp/kujuatime/data
EXPOSE 5000
CMD ["npm", "run", "start"]
