services:
  client:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.client
      args:
        VITE_API_URL: ""

  server:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.server
    env_file:
      - ../../server/.env

  nginx:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - server
